In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [32]:
x = torch.empty(5, 3)
# print(x)

Construct a randomly initialized matrix:



In [33]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.7153,  0.1779,  0.0279],
        [ 0.8378,  0.3285,  0.3698],
        [ 0.3795,  0.7288,  0.7489],
        [ 0.0011,  0.4072,  0.7509],
        [ 0.6175,  0.0880,  0.3227]])


Construct a matrix filled zeros and of dtype long:



In [34]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [35]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor basing on existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [36]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [37]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.8173,  0.5572,  1.8154],
        [-1.6291, -0.7193,  0.1105],
        [-0.6700,  0.6568, -0.5077],
        [-0.1210, -0.5245,  1.4933],
        [-3.4497, -1.1744, -0.6400]])


Get its size:



In [38]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [39]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.6394,  1.2830,  2.1806],
        [-0.8914, -0.3099,  0.7910],
        [ 0.3286,  1.1813,  0.4212],
        [ 0.6183, -0.2175,  1.9242],
        [-2.8087, -0.6018, -0.1652]])


Addition: syntax 2



In [40]:
print(torch.add(x, y))

tensor([[ 1.6394,  1.2830,  2.1806],
        [-0.8914, -0.3099,  0.7910],
        [ 0.3286,  1.1813,  0.4212],
        [ 0.6183, -0.2175,  1.9242],
        [-2.8087, -0.6018, -0.1652]])


Addition: providing an output tensor as argument



In [41]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6394,  1.2830,  2.1806],
        [-0.8914, -0.3099,  0.7910],
        [ 0.3286,  1.1813,  0.4212],
        [ 0.6183, -0.2175,  1.9242],
        [-2.8087, -0.6018, -0.1652]])


Addition: in-place



In [42]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.6394,  1.2830,  2.1806],
        [-0.8914, -0.3099,  0.7910],
        [ 0.3286,  1.1813,  0.4212],
        [ 0.6183, -0.2175,  1.9242],
        [-2.8087, -0.6018, -0.1652]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [44]:
print(x[:, 1])

tensor([ 0.5572, -0.7193,  0.6568, -0.5245, -1.1744])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [6]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [7]:
x

tensor([[-0.9702, -0.5653, -0.7218,  0.6905],
        [ 0.9146,  0.3590,  0.1111,  0.0684],
        [ 1.6570,  0.0136, -0.7831, -2.1182],
        [ 0.3373,  0.9352,  0.1759, -0.5756]])

In [47]:
y

tensor([ 0.7546, -0.4978,  0.5019, -1.8004, -1.8255, -0.7342,  0.4556,
         1.2283,  1.1305, -0.3993, -1.1601, -0.4676,  0.1939,  0.7138,
        -1.0682,  1.4366])

In [48]:
z

tensor([[ 0.7546, -0.4978,  0.5019, -1.8004, -1.8255, -0.7342,  0.4556,
          1.2283],
        [ 1.1305, -0.3993, -1.1601, -0.4676,  0.1939,  0.7138, -1.0682,
          1.4366]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [4]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.7224])
0.7224390506744385


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [50]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [51]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [52]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [53]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [8]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('no cuda')

tensor([[ 0.0298,  0.4347,  0.2782,  1.6905],
        [ 1.9146,  1.3590,  1.1111,  1.0684],
        [ 2.6570,  1.0136,  0.2169, -1.1182],
        [ 1.3373,  1.9352,  1.1759,  0.4244]], device='cuda:0')
tensor([[ 0.0298,  0.4347,  0.2782,  1.6905],
        [ 1.9146,  1.3590,  1.1111,  1.0684],
        [ 2.6570,  1.0136,  0.2169, -1.1182],
        [ 1.3373,  1.9352,  1.1759,  0.4244]], dtype=torch.float64)
